[alembic]
script_location = migracoes
version_locations = %(here)s/migracoes/versoes
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generico

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generico

[formatter_generico]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

