"""add_tempos_personalizados

Revisão: 40ae90ed5e83
Revisão anterior: 0001_schema_inicial
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '40ae90ed5e83'
down_revision: Union[str, Sequence[str], None] = '0001_schema_inicial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempos_personalizados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participante_id', sa.Uuid(), nullable=False),
    sa.Column('tempo_alvo_ms', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tempos_personalizados_criado_em', 'tempos_personalizados', ['criado_em'], unique=False)
    op.create_index(op.f('ix_tempos_personalizados_participante_id'), 'tempos_personalizados', ['participante_id'], unique=False)
    op.create_index('uq_tempo_personalizado_ativo', 'tempos_personalizados', ['participante_id', 'tempo_alvo_ms'], unique=True, postgresql_where=sa.text('ativo = true'))
    op.add_column('tentativas', sa.Column('tempo_personalizado_id', sa.Uuid(), nullable=True))
    op.add_column('tentativas', sa.Column('tipo_tentativa', sa.Enum('OFICIAL', 'PERSONALIZADA', name='tipo_tentativa', native_enum=False), server_default='OFICIAL', nullable=False))
    op.drop_constraint(op.f('uq_tentativa_participante_combinacao'), 'tentativas', type_='unique')
    op.create_index(op.f('ix_tentativas_tempo_personalizado_id'), 'tentativas', ['tempo_personalizado_id'], unique=False)
    op.create_index('uq_tentativa_oficial', 'tentativas', ['participante_id', 'tempo_alvo_ms', 'condicao'], unique=True, postgresql_where=sa.text("tipo_tentativa = 'OFICIAL'"))
    op.drop_constraint('ck_tempo_alvo', 'tentativas', type_='check')
    op.create_check_constraint(
        'ck_tempo_alvo',
        'tentativas',
        "(tipo_tentativa = 'OFICIAL' AND tempo_alvo_ms IN (5000, 15000, 30000)) OR (tipo_tentativa = 'PERSONALIZADA' AND tempo_alvo_ms > 0)"
    )
    op.create_foreign_key(op.f('fk_tentativas_tempo_personalizado_id'), 'tentativas', 'tempos_personalizados', ['tempo_personalizado_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tentativas_tempo_personalizado_id'), 'tentativas', type_='foreignkey')
    op.drop_constraint('ck_tempo_alvo', 'tentativas', type_='check')
    op.create_check_constraint(
        'ck_tempo_alvo',
        'tentativas',
        "tempo_alvo_ms IN (5000, 15000, 30000)"
    )
    op.drop_index('uq_tentativa_oficial', table_name='tentativas', postgresql_where=sa.text("tipo_tentativa = 'OFICIAL'"))
    op.drop_index(op.f('ix_tentativas_tempo_personalizado_id'), table_name='tentativas')
    op.create_unique_constraint(op.f('uq_tentativa_participante_combinacao'), 'tentativas', ['participante_id', 'tempo_alvo_ms', 'condicao'], postgresql_nulls_not_distinct=False)
    op.drop_column('tentativas', 'tipo_tentativa')
    op.drop_column('tentativas', 'tempo_personalizado_id')
    op.drop_index('uq_tempo_personalizado_ativo', table_name='tempos_personalizados', postgresql_where=sa.text('ativo = true'))
    op.drop_index(op.f('ix_tempos_personalizados_participante_id'), table_name='tempos_personalizados')
    op.drop_index('ix_tempos_personalizados_criado_em', table_name='tempos_personalizados')
    op.drop_table('tempos_personalizados')
    # ### end Alembic commands ###

